
namespace chatapp
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnClose = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModul2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModul3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModul4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLatMod1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLatMod2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLatMod3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLatMod4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(238)))), ((int)(((byte)(153)))));
            this.panel1.Controls.Add(this.btnClose);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(500, 123);
            this.panel1.TabIndex = 0;
            // 
            // btnClose
            // 
            this.btnClose.ActiveImage = null;
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowBuffering = false;
            this.btnClose.AllowToggling = false;
            this.btnClose.AllowZooming = true;
            this.btnClose.AllowZoomingOnFocus = false;
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnClose.ErrorImage")));
            this.btnClose.FadeWhenInactive = false;
            this.btnClose.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnClose.Image = ((System.Drawing.Image)(resources.GetObject("btnClose.Image")));
            this.btnClose.ImageActive = null;
            this.btnClose.ImageLocation = null;
            this.btnClose.ImageMargin = 10;
            this.btnClose.ImageSize = new System.Drawing.Size(20, 20);
            this.btnClose.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.btnClose.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnClose.InitialImage")));
            this.btnClose.Location = new System.Drawing.Point(458, 12);
            this.btnClose.Name = "btnClose";
            this.btnClose.Rotation = 0;
            this.btnClose.ShowActiveImage = true;
            this.btnClose.ShowCursorChanges = true;
            this.btnClose.ShowImageBorders = true;
            this.btnClose.ShowSizeMarkers = false;
            this.btnClose.Size = new System.Drawing.Size(30, 30);
            this.btnClose.TabIndex = 2;
            this.btnClose.ToolTipText = "";
            this.btnClose.WaitOnLoad = false;
            this.btnClose.Zoom = 10;
            this.btnClose.ZoomSpeed = 10;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(86, 31);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(352, 54);
            this.label1.TabIndex = 0;
            this.label1.Text = "Belajar Esperanto";
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Modul 1: Perkenalan";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleBorderRadius = 30;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(75, 153);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 30;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.bunifuButton1.onHoverState.BorderRadius = 30;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 30;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 30;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(350, 60);
            this.bunifuButton1.TabIndex = 1;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btnModul2
            // 
            this.btnModul2.AllowAnimations = true;
            this.btnModul2.AllowMouseEffects = true;
            this.btnModul2.AllowToggling = false;
            this.btnModul2.AnimationSpeed = 200;
            this.btnModul2.AutoGenerateColors = false;
            this.btnModul2.AutoRoundBorders = false;
            this.btnModul2.AutoSizeLeftIcon = true;
            this.btnModul2.AutoSizeRightIcon = true;
            this.btnModul2.BackColor = System.Drawing.Color.Transparent;
            this.btnModul2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModul2.BackgroundImage")));
            this.btnModul2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul2.ButtonText = "Modul 2";
            this.btnModul2.ButtonTextMarginLeft = 0;
            this.btnModul2.ColorContrastOnClick = 45;
            this.btnModul2.ColorContrastOnHover = 45;
            this.btnModul2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnModul2.CustomizableEdges = borderEdges2;
            this.btnModul2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModul2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModul2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModul2.ForeColor = System.Drawing.Color.White;
            this.btnModul2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModul2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModul2.IconMarginLeft = 11;
            this.btnModul2.IconPadding = 10;
            this.btnModul2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModul2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModul2.IconSize = 25;
            this.btnModul2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul2.IdleBorderRadius = 30;
            this.btnModul2.IdleBorderThickness = 1;
            this.btnModul2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul2.IdleIconLeftImage = null;
            this.btnModul2.IdleIconRightImage = null;
            this.btnModul2.IndicateFocus = false;
            this.btnModul2.Location = new System.Drawing.Point(75, 291);
            this.btnModul2.Name = "btnModul2";
            this.btnModul2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul2.OnDisabledState.BorderRadius = 30;
            this.btnModul2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul2.OnDisabledState.BorderThickness = 1;
            this.btnModul2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul2.OnDisabledState.IconLeftImage = null;
            this.btnModul2.OnDisabledState.IconRightImage = null;
            this.btnModul2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul2.onHoverState.BorderRadius = 30;
            this.btnModul2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul2.onHoverState.BorderThickness = 1;
            this.btnModul2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModul2.onHoverState.IconLeftImage = null;
            this.btnModul2.onHoverState.IconRightImage = null;
            this.btnModul2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul2.OnIdleState.BorderRadius = 30;
            this.btnModul2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul2.OnIdleState.BorderThickness = 1;
            this.btnModul2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModul2.OnIdleState.IconLeftImage = null;
            this.btnModul2.OnIdleState.IconRightImage = null;
            this.btnModul2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul2.OnPressedState.BorderRadius = 30;
            this.btnModul2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul2.OnPressedState.BorderThickness = 1;
            this.btnModul2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModul2.OnPressedState.IconLeftImage = null;
            this.btnModul2.OnPressedState.IconRightImage = null;
            this.btnModul2.Size = new System.Drawing.Size(350, 60);
            this.btnModul2.TabIndex = 2;
            this.btnModul2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModul2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModul2.TextMarginLeft = 0;
            this.btnModul2.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModul2.UseDefaultRadiusAndThickness = true;
            // 
            // btnModul3
            // 
            this.btnModul3.AllowAnimations = true;
            this.btnModul3.AllowMouseEffects = true;
            this.btnModul3.AllowToggling = false;
            this.btnModul3.AnimationSpeed = 200;
            this.btnModul3.AutoGenerateColors = false;
            this.btnModul3.AutoRoundBorders = false;
            this.btnModul3.AutoSizeLeftIcon = true;
            this.btnModul3.AutoSizeRightIcon = true;
            this.btnModul3.BackColor = System.Drawing.Color.Transparent;
            this.btnModul3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModul3.BackgroundImage")));
            this.btnModul3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul3.ButtonText = "Modul 3";
            this.btnModul3.ButtonTextMarginLeft = 0;
            this.btnModul3.ColorContrastOnClick = 45;
            this.btnModul3.ColorContrastOnHover = 45;
            this.btnModul3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnModul3.CustomizableEdges = borderEdges3;
            this.btnModul3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModul3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModul3.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModul3.ForeColor = System.Drawing.Color.White;
            this.btnModul3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModul3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModul3.IconMarginLeft = 11;
            this.btnModul3.IconPadding = 10;
            this.btnModul3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModul3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModul3.IconSize = 25;
            this.btnModul3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul3.IdleBorderRadius = 30;
            this.btnModul3.IdleBorderThickness = 1;
            this.btnModul3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul3.IdleIconLeftImage = null;
            this.btnModul3.IdleIconRightImage = null;
            this.btnModul3.IndicateFocus = false;
            this.btnModul3.Location = new System.Drawing.Point(75, 431);
            this.btnModul3.Name = "btnModul3";
            this.btnModul3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul3.OnDisabledState.BorderRadius = 30;
            this.btnModul3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul3.OnDisabledState.BorderThickness = 1;
            this.btnModul3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul3.OnDisabledState.IconLeftImage = null;
            this.btnModul3.OnDisabledState.IconRightImage = null;
            this.btnModul3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul3.onHoverState.BorderRadius = 30;
            this.btnModul3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul3.onHoverState.BorderThickness = 1;
            this.btnModul3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModul3.onHoverState.IconLeftImage = null;
            this.btnModul3.onHoverState.IconRightImage = null;
            this.btnModul3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul3.OnIdleState.BorderRadius = 30;
            this.btnModul3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul3.OnIdleState.BorderThickness = 1;
            this.btnModul3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModul3.OnIdleState.IconLeftImage = null;
            this.btnModul3.OnIdleState.IconRightImage = null;
            this.btnModul3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul3.OnPressedState.BorderRadius = 30;
            this.btnModul3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul3.OnPressedState.BorderThickness = 1;
            this.btnModul3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModul3.OnPressedState.IconLeftImage = null;
            this.btnModul3.OnPressedState.IconRightImage = null;
            this.btnModul3.Size = new System.Drawing.Size(350, 60);
            this.btnModul3.TabIndex = 3;
            this.btnModul3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModul3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModul3.TextMarginLeft = 0;
            this.btnModul3.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModul3.UseDefaultRadiusAndThickness = true;
            // 
            // btnModul4
            // 
            this.btnModul4.AllowAnimations = true;
            this.btnModul4.AllowMouseEffects = true;
            this.btnModul4.AllowToggling = false;
            this.btnModul4.AnimationSpeed = 200;
            this.btnModul4.AutoGenerateColors = false;
            this.btnModul4.AutoRoundBorders = false;
            this.btnModul4.AutoSizeLeftIcon = true;
            this.btnModul4.AutoSizeRightIcon = true;
            this.btnModul4.BackColor = System.Drawing.Color.Transparent;
            this.btnModul4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModul4.BackgroundImage")));
            this.btnModul4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul4.ButtonText = "Modul 4";
            this.btnModul4.ButtonTextMarginLeft = 0;
            this.btnModul4.ColorContrastOnClick = 45;
            this.btnModul4.ColorContrastOnHover = 45;
            this.btnModul4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnModul4.CustomizableEdges = borderEdges4;
            this.btnModul4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModul4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModul4.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModul4.ForeColor = System.Drawing.Color.White;
            this.btnModul4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModul4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModul4.IconMarginLeft = 11;
            this.btnModul4.IconPadding = 10;
            this.btnModul4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModul4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModul4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModul4.IconSize = 25;
            this.btnModul4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul4.IdleBorderRadius = 30;
            this.btnModul4.IdleBorderThickness = 1;
            this.btnModul4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul4.IdleIconLeftImage = null;
            this.btnModul4.IdleIconRightImage = null;
            this.btnModul4.IndicateFocus = false;
            this.btnModul4.Location = new System.Drawing.Point(75, 566);
            this.btnModul4.Name = "btnModul4";
            this.btnModul4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModul4.OnDisabledState.BorderRadius = 30;
            this.btnModul4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul4.OnDisabledState.BorderThickness = 1;
            this.btnModul4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModul4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModul4.OnDisabledState.IconLeftImage = null;
            this.btnModul4.OnDisabledState.IconRightImage = null;
            this.btnModul4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul4.onHoverState.BorderRadius = 30;
            this.btnModul4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul4.onHoverState.BorderThickness = 1;
            this.btnModul4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModul4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModul4.onHoverState.IconLeftImage = null;
            this.btnModul4.onHoverState.IconRightImage = null;
            this.btnModul4.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul4.OnIdleState.BorderRadius = 30;
            this.btnModul4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul4.OnIdleState.BorderThickness = 1;
            this.btnModul4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.btnModul4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModul4.OnIdleState.IconLeftImage = null;
            this.btnModul4.OnIdleState.IconRightImage = null;
            this.btnModul4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul4.OnPressedState.BorderRadius = 30;
            this.btnModul4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModul4.OnPressedState.BorderThickness = 1;
            this.btnModul4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModul4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModul4.OnPressedState.IconLeftImage = null;
            this.btnModul4.OnPressedState.IconRightImage = null;
            this.btnModul4.Size = new System.Drawing.Size(350, 60);
            this.btnModul4.TabIndex = 4;
            this.btnModul4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModul4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModul4.TextMarginLeft = 0;
            this.btnModul4.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModul4.UseDefaultRadiusAndThickness = true;
            // 
            // btnLatMod1
            // 
            this.btnLatMod1.AllowAnimations = true;
            this.btnLatMod1.AllowMouseEffects = true;
            this.btnLatMod1.AllowToggling = false;
            this.btnLatMod1.AnimationSpeed = 200;
            this.btnLatMod1.AutoGenerateColors = false;
            this.btnLatMod1.AutoRoundBorders = false;
            this.btnLatMod1.AutoSizeLeftIcon = true;
            this.btnLatMod1.AutoSizeRightIcon = true;
            this.btnLatMod1.BackColor = System.Drawing.Color.Transparent;
            this.btnLatMod1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLatMod1.BackgroundImage")));
            this.btnLatMod1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod1.ButtonText = "Modul 1: Latihan";
            this.btnLatMod1.ButtonTextMarginLeft = 0;
            this.btnLatMod1.ColorContrastOnClick = 45;
            this.btnLatMod1.ColorContrastOnHover = 45;
            this.btnLatMod1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnLatMod1.CustomizableEdges = borderEdges5;
            this.btnLatMod1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLatMod1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLatMod1.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLatMod1.ForeColor = System.Drawing.Color.White;
            this.btnLatMod1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLatMod1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLatMod1.IconMarginLeft = 11;
            this.btnLatMod1.IconPadding = 10;
            this.btnLatMod1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLatMod1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLatMod1.IconSize = 25;
            this.btnLatMod1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod1.IdleBorderRadius = 30;
            this.btnLatMod1.IdleBorderThickness = 1;
            this.btnLatMod1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod1.IdleIconLeftImage = null;
            this.btnLatMod1.IdleIconRightImage = null;
            this.btnLatMod1.IndicateFocus = false;
            this.btnLatMod1.Location = new System.Drawing.Point(76, 219);
            this.btnLatMod1.Name = "btnLatMod1";
            this.btnLatMod1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod1.OnDisabledState.BorderRadius = 30;
            this.btnLatMod1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod1.OnDisabledState.BorderThickness = 1;
            this.btnLatMod1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod1.OnDisabledState.IconLeftImage = null;
            this.btnLatMod1.OnDisabledState.IconRightImage = null;
            this.btnLatMod1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod1.onHoverState.BorderRadius = 30;
            this.btnLatMod1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod1.onHoverState.BorderThickness = 1;
            this.btnLatMod1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod1.onHoverState.IconLeftImage = null;
            this.btnLatMod1.onHoverState.IconRightImage = null;
            this.btnLatMod1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod1.OnIdleState.BorderRadius = 30;
            this.btnLatMod1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod1.OnIdleState.BorderThickness = 1;
            this.btnLatMod1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod1.OnIdleState.IconLeftImage = null;
            this.btnLatMod1.OnIdleState.IconRightImage = null;
            this.btnLatMod1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod1.OnPressedState.BorderRadius = 30;
            this.btnLatMod1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod1.OnPressedState.BorderThickness = 1;
            this.btnLatMod1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod1.OnPressedState.IconLeftImage = null;
            this.btnLatMod1.OnPressedState.IconRightImage = null;
            this.btnLatMod1.Size = new System.Drawing.Size(350, 44);
            this.btnLatMod1.TabIndex = 6;
            this.btnLatMod1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLatMod1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLatMod1.TextMarginLeft = 0;
            this.btnLatMod1.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLatMod1.UseDefaultRadiusAndThickness = true;
            this.btnLatMod1.Click += new System.EventHandler(this.btnLatMod1_Click);
            // 
            // btnLatMod2
            // 
            this.btnLatMod2.AllowAnimations = true;
            this.btnLatMod2.AllowMouseEffects = true;
            this.btnLatMod2.AllowToggling = false;
            this.btnLatMod2.AnimationSpeed = 200;
            this.btnLatMod2.AutoGenerateColors = false;
            this.btnLatMod2.AutoRoundBorders = false;
            this.btnLatMod2.AutoSizeLeftIcon = true;
            this.btnLatMod2.AutoSizeRightIcon = true;
            this.btnLatMod2.BackColor = System.Drawing.Color.Transparent;
            this.btnLatMod2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLatMod2.BackgroundImage")));
            this.btnLatMod2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod2.ButtonText = "Modul 2: Latihan";
            this.btnLatMod2.ButtonTextMarginLeft = 0;
            this.btnLatMod2.ColorContrastOnClick = 45;
            this.btnLatMod2.ColorContrastOnHover = 45;
            this.btnLatMod2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnLatMod2.CustomizableEdges = borderEdges6;
            this.btnLatMod2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLatMod2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLatMod2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLatMod2.ForeColor = System.Drawing.Color.White;
            this.btnLatMod2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLatMod2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLatMod2.IconMarginLeft = 11;
            this.btnLatMod2.IconPadding = 10;
            this.btnLatMod2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLatMod2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLatMod2.IconSize = 25;
            this.btnLatMod2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod2.IdleBorderRadius = 30;
            this.btnLatMod2.IdleBorderThickness = 1;
            this.btnLatMod2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod2.IdleIconLeftImage = null;
            this.btnLatMod2.IdleIconRightImage = null;
            this.btnLatMod2.IndicateFocus = false;
            this.btnLatMod2.Location = new System.Drawing.Point(76, 357);
            this.btnLatMod2.Name = "btnLatMod2";
            this.btnLatMod2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod2.OnDisabledState.BorderRadius = 30;
            this.btnLatMod2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod2.OnDisabledState.BorderThickness = 1;
            this.btnLatMod2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod2.OnDisabledState.IconLeftImage = null;
            this.btnLatMod2.OnDisabledState.IconRightImage = null;
            this.btnLatMod2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod2.onHoverState.BorderRadius = 30;
            this.btnLatMod2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod2.onHoverState.BorderThickness = 1;
            this.btnLatMod2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod2.onHoverState.IconLeftImage = null;
            this.btnLatMod2.onHoverState.IconRightImage = null;
            this.btnLatMod2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod2.OnIdleState.BorderRadius = 30;
            this.btnLatMod2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod2.OnIdleState.BorderThickness = 1;
            this.btnLatMod2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod2.OnIdleState.IconLeftImage = null;
            this.btnLatMod2.OnIdleState.IconRightImage = null;
            this.btnLatMod2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod2.OnPressedState.BorderRadius = 30;
            this.btnLatMod2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod2.OnPressedState.BorderThickness = 1;
            this.btnLatMod2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod2.OnPressedState.IconLeftImage = null;
            this.btnLatMod2.OnPressedState.IconRightImage = null;
            this.btnLatMod2.Size = new System.Drawing.Size(350, 44);
            this.btnLatMod2.TabIndex = 7;
            this.btnLatMod2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLatMod2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLatMod2.TextMarginLeft = 0;
            this.btnLatMod2.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLatMod2.UseDefaultRadiusAndThickness = true;
            // 
            // btnLatMod3
            // 
            this.btnLatMod3.AllowAnimations = true;
            this.btnLatMod3.AllowMouseEffects = true;
            this.btnLatMod3.AllowToggling = false;
            this.btnLatMod3.AnimationSpeed = 200;
            this.btnLatMod3.AutoGenerateColors = false;
            this.btnLatMod3.AutoRoundBorders = false;
            this.btnLatMod3.AutoSizeLeftIcon = true;
            this.btnLatMod3.AutoSizeRightIcon = true;
            this.btnLatMod3.BackColor = System.Drawing.Color.Transparent;
            this.btnLatMod3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLatMod3.BackgroundImage")));
            this.btnLatMod3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod3.ButtonText = "Modul 3: Latihan";
            this.btnLatMod3.ButtonTextMarginLeft = 0;
            this.btnLatMod3.ColorContrastOnClick = 45;
            this.btnLatMod3.ColorContrastOnHover = 45;
            this.btnLatMod3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnLatMod3.CustomizableEdges = borderEdges7;
            this.btnLatMod3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLatMod3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLatMod3.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLatMod3.ForeColor = System.Drawing.Color.White;
            this.btnLatMod3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLatMod3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLatMod3.IconMarginLeft = 11;
            this.btnLatMod3.IconPadding = 10;
            this.btnLatMod3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLatMod3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLatMod3.IconSize = 25;
            this.btnLatMod3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod3.IdleBorderRadius = 30;
            this.btnLatMod3.IdleBorderThickness = 1;
            this.btnLatMod3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod3.IdleIconLeftImage = null;
            this.btnLatMod3.IdleIconRightImage = null;
            this.btnLatMod3.IndicateFocus = false;
            this.btnLatMod3.Location = new System.Drawing.Point(75, 497);
            this.btnLatMod3.Name = "btnLatMod3";
            this.btnLatMod3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod3.OnDisabledState.BorderRadius = 30;
            this.btnLatMod3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod3.OnDisabledState.BorderThickness = 1;
            this.btnLatMod3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod3.OnDisabledState.IconLeftImage = null;
            this.btnLatMod3.OnDisabledState.IconRightImage = null;
            this.btnLatMod3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod3.onHoverState.BorderRadius = 30;
            this.btnLatMod3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod3.onHoverState.BorderThickness = 1;
            this.btnLatMod3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod3.onHoverState.IconLeftImage = null;
            this.btnLatMod3.onHoverState.IconRightImage = null;
            this.btnLatMod3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod3.OnIdleState.BorderRadius = 30;
            this.btnLatMod3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod3.OnIdleState.BorderThickness = 1;
            this.btnLatMod3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod3.OnIdleState.IconLeftImage = null;
            this.btnLatMod3.OnIdleState.IconRightImage = null;
            this.btnLatMod3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod3.OnPressedState.BorderRadius = 30;
            this.btnLatMod3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod3.OnPressedState.BorderThickness = 1;
            this.btnLatMod3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod3.OnPressedState.IconLeftImage = null;
            this.btnLatMod3.OnPressedState.IconRightImage = null;
            this.btnLatMod3.Size = new System.Drawing.Size(350, 44);
            this.btnLatMod3.TabIndex = 8;
            this.btnLatMod3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLatMod3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLatMod3.TextMarginLeft = 0;
            this.btnLatMod3.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLatMod3.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton5
            // 
            this.bunifuButton5.AllowAnimations = true;
            this.bunifuButton5.AllowMouseEffects = true;
            this.bunifuButton5.AllowToggling = false;
            this.bunifuButton5.AnimationSpeed = 200;
            this.bunifuButton5.AutoGenerateColors = false;
            this.bunifuButton5.AutoRoundBorders = false;
            this.bunifuButton5.AutoSizeLeftIcon = true;
            this.bunifuButton5.AutoSizeRightIcon = true;
            this.bunifuButton5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton5.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.BackgroundImage")));
            this.bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.ButtonText = "Modul 5";
            this.bunifuButton5.ButtonTextMarginLeft = 0;
            this.bunifuButton5.ColorContrastOnClick = 45;
            this.bunifuButton5.ColorContrastOnHover = 45;
            this.bunifuButton5.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton5.CustomizableEdges = borderEdges8;
            this.bunifuButton5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton5.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton5.Enabled = false;
            this.bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton5.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton5.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton5.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton5.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton5.IconMarginLeft = 11;
            this.bunifuButton5.IconPadding = 10;
            this.bunifuButton5.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton5.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton5.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton5.IconSize = 25;
            this.bunifuButton5.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton5.IdleBorderRadius = 30;
            this.bunifuButton5.IdleBorderThickness = 1;
            this.bunifuButton5.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton5.IdleIconLeftImage = null;
            this.bunifuButton5.IdleIconRightImage = null;
            this.bunifuButton5.IndicateFocus = false;
            this.bunifuButton5.Location = new System.Drawing.Point(75, 710);
            this.bunifuButton5.Name = "bunifuButton5";
            this.bunifuButton5.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton5.OnDisabledState.BorderRadius = 30;
            this.bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnDisabledState.BorderThickness = 1;
            this.bunifuButton5.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton5.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton5.OnDisabledState.IconLeftImage = null;
            this.bunifuButton5.OnDisabledState.IconRightImage = null;
            this.bunifuButton5.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton5.onHoverState.BorderRadius = 30;
            this.bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.onHoverState.BorderThickness = 1;
            this.bunifuButton5.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton5.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.onHoverState.IconLeftImage = null;
            this.bunifuButton5.onHoverState.IconRightImage = null;
            this.bunifuButton5.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton5.OnIdleState.BorderRadius = 30;
            this.bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnIdleState.BorderThickness = 1;
            this.bunifuButton5.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(119)))), ((int)(((byte)(221)))), ((int)(((byte)(102)))));
            this.bunifuButton5.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.OnIdleState.IconLeftImage = null;
            this.bunifuButton5.OnIdleState.IconRightImage = null;
            this.bunifuButton5.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton5.OnPressedState.BorderRadius = 30;
            this.bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnPressedState.BorderThickness = 1;
            this.bunifuButton5.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton5.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.OnPressedState.IconLeftImage = null;
            this.bunifuButton5.OnPressedState.IconRightImage = null;
            this.bunifuButton5.Size = new System.Drawing.Size(350, 60);
            this.bunifuButton5.TabIndex = 5;
            this.bunifuButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton5.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton5.TextMarginLeft = 0;
            this.bunifuButton5.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton5.UseDefaultRadiusAndThickness = true;
            // 
            // btnLatMod4
            // 
            this.btnLatMod4.AllowAnimations = true;
            this.btnLatMod4.AllowMouseEffects = true;
            this.btnLatMod4.AllowToggling = false;
            this.btnLatMod4.AnimationSpeed = 200;
            this.btnLatMod4.AutoGenerateColors = false;
            this.btnLatMod4.AutoRoundBorders = false;
            this.btnLatMod4.AutoSizeLeftIcon = true;
            this.btnLatMod4.AutoSizeRightIcon = true;
            this.btnLatMod4.BackColor = System.Drawing.Color.Transparent;
            this.btnLatMod4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLatMod4.BackgroundImage")));
            this.btnLatMod4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod4.ButtonText = "Modul 4: Latihan";
            this.btnLatMod4.ButtonTextMarginLeft = 0;
            this.btnLatMod4.ColorContrastOnClick = 45;
            this.btnLatMod4.ColorContrastOnHover = 45;
            this.btnLatMod4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnLatMod4.CustomizableEdges = borderEdges9;
            this.btnLatMod4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLatMod4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLatMod4.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLatMod4.ForeColor = System.Drawing.Color.White;
            this.btnLatMod4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLatMod4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLatMod4.IconMarginLeft = 11;
            this.btnLatMod4.IconPadding = 10;
            this.btnLatMod4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLatMod4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLatMod4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLatMod4.IconSize = 25;
            this.btnLatMod4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod4.IdleBorderRadius = 30;
            this.btnLatMod4.IdleBorderThickness = 1;
            this.btnLatMod4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod4.IdleIconLeftImage = null;
            this.btnLatMod4.IdleIconRightImage = null;
            this.btnLatMod4.IndicateFocus = false;
            this.btnLatMod4.Location = new System.Drawing.Point(75, 632);
            this.btnLatMod4.Name = "btnLatMod4";
            this.btnLatMod4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLatMod4.OnDisabledState.BorderRadius = 30;
            this.btnLatMod4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod4.OnDisabledState.BorderThickness = 1;
            this.btnLatMod4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLatMod4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLatMod4.OnDisabledState.IconLeftImage = null;
            this.btnLatMod4.OnDisabledState.IconRightImage = null;
            this.btnLatMod4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod4.onHoverState.BorderRadius = 30;
            this.btnLatMod4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod4.onHoverState.BorderThickness = 1;
            this.btnLatMod4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod4.onHoverState.IconLeftImage = null;
            this.btnLatMod4.onHoverState.IconRightImage = null;
            this.btnLatMod4.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod4.OnIdleState.BorderRadius = 30;
            this.btnLatMod4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod4.OnIdleState.BorderThickness = 1;
            this.btnLatMod4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnLatMod4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod4.OnIdleState.IconLeftImage = null;
            this.btnLatMod4.OnIdleState.IconRightImage = null;
            this.btnLatMod4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod4.OnPressedState.BorderRadius = 30;
            this.btnLatMod4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLatMod4.OnPressedState.BorderThickness = 1;
            this.btnLatMod4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(233)))), ((int)(((byte)(156)))));
            this.btnLatMod4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLatMod4.OnPressedState.IconLeftImage = null;
            this.btnLatMod4.OnPressedState.IconRightImage = null;
            this.btnLatMod4.Size = new System.Drawing.Size(350, 44);
            this.btnLatMod4.TabIndex = 9;
            this.btnLatMod4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLatMod4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLatMod4.TextMarginLeft = 0;
            this.btnLatMod4.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLatMod4.UseDefaultRadiusAndThickness = true;
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(500, 800);
            this.Controls.Add(this.btnLatMod4);
            this.Controls.Add(this.btnLatMod3);
            this.Controls.Add(this.btnLatMod2);
            this.Controls.Add(this.btnLatMod1);
            this.Controls.Add(this.bunifuButton5);
            this.Controls.Add(this.btnModul4);
            this.Controls.Add(this.btnModul3);
            this.Controls.Add(this.btnModul2);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form2";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModul2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModul3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModul4;
        private Bunifu.UI.WinForms.BunifuImageButton btnClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLatMod1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLatMod2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLatMod3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLatMod4;
    }
}